from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from . import lift_node
from . import latent_io

NODE_CLASS_MAPPINGS.update(lift_node.NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(lift_node.NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(latent_io.NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(latent_io.NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
